import Footer from "../components/Footer/Footer";
import NavBar from "../components/NavBar/NavBar";
import "../styles/globals.css";
import Head from "next/head";
import toss from "../components/common-consts/toss";

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>{toss}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />
      <Component {...pageProps} />
      <Footer />
    </>
  );
}

export default MyApp;
